version: '3.1'

services:
  db:
    image: mysql:5.7
    ports:
      - "3306:3306"
    volumes:
      - db_volume:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: MaYc6PPuqPwwxk2J
      MYSQL_DATABASE: crud-cit
      MYSQL_USER: cit
      MYSQL_PASSWORD: njhFjX6j

volumes:
    db_volume:
